### ISSUE TITLE
Button label - inconsistent language (CS / EN)

### ISSUE THREAD

**Issue by KamilHavlicek** [citicashio/blockchain-explorer#1]
It would be better to keep the button caption in English:
https://github.com/citicashio/blockchain-explorer/blob/97e0f3b7b76d75dff4f3d2dad73311f398fa41f1/app/templates/%40layout.latte#L58

**Comment by mzk** [comment]
@KamilHavlicek Thank you for reporting the issue. It was fixed https://github.com/citicashio/blockchain-explorer/commit/f87a3cda78b5c2dd7cc41f5234358b40b218ecef 

Have a nice day.
